os: linux
language: python
notifications: 
  email: false
env:
  - ASSIGNMENT=assignment11
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda env create -f environment.yml
  - source $(conda info --root)/etc/profile.d/conda.sh
  - conda activate $ASSIGNMENT
  - "curl -H \"Authorization: token ${GH_TOKEN}\" -H 'Accept: application/vnd.github.v3.raw' -O --location \"https://api.github.com/repos/PGE310/${ASSIGNMENT}/contents/test.py\""
  - "curl -H \"Authorization: token ${GH_TOKEN}\" -H 'Accept: application/vnd.github.v3.raw' -O --location \"https://api.github.com/repos/PGE310/${ASSIGNMENT}/contents/images/eog_wells_in_nd_gold.png\""
  - "curl -H \"Authorization: token ${GH_TOKEN}\" -H 'Accept: application/vnd.github.v3.raw' -O --location \"https://api.github.com/repos/PGE310/${ASSIGNMENT}/contents/eog_wells_in_tx.csv\""
  - "(cd images && curl -H \"Authorization: token ${GH_TOKEN}\" -H 'Accept: application/vnd.github.v3.raw' -O --location \"https://api.github.com/repos/PGE310/${ASSIGNMENT}/contents/images/eog_wells_in_tx_gold.png\")"
script:
  - python -m unittest test.py -vvv
